const beef = {
  PROD_NO:6,
  SKU_NO:10,
  sel:1,
  image:'https://gd3.alicdn.com/imgextra/i3/2578475925/TB2gcvrbX_AQeBjSZFBXXX22XXa_!!2578475925.jpg',
  name:'内蒙古风干牛肉干',
  price:'￥29.8',
  activity:'买就送50g现烤牛肉干',
  count:'月销量1373',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/2578475925/TB2eaedXOnB11BjSsphXXXpaXXa_!!2578475925.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2578475925/TB2TqidXOnB11BjSsphXXXpaXXa_!!2578475925.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2578475925/TB2grCfXLPB11BjSsppXXcjYVXa_!!2578475925.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'甜辣',
      brand:'微辣',
      city:'麻辣',
    },
    ARG:[
      {
        n:'商品名称',
        c:'内蒙古风干牛肉干',
      },
      {
        n:'商品产地',
        c:'呼和浩特市',
      },
      {
        n:'生产厂商',
        c:'穆氏傻子王',
      },
      {
        n:'商品口味',
        c:'微辣',
      }
    ]
  },
  comment:[
    {
      name:'哈哈啊哈哈',
      stars:4.5,
      date:'2016年12月30日',
      content:'很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；',
      picture:[
      ],
      browse:2041,
      praise:21,
    },
    {
      name:'hahhaha',
      stars:3,
      date:'2016年12月30日',
      content:'很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；很好吃，还想再吃一次；',
      picture:[],
      browse:2041,
      praise:1,
    },
  ],
};

const hot = {
  PROD_NO:7,
  SKU_NO:11,
  sel:1,
  image:'https://gd4.alicdn.com/imgextra/i4/2705663075/TB20zlYbrBmpuFjSZFAXXaQ0pXa_!!2705663075.jpg',
  name:'肉辣条重庆风味小吃',
  price:'￥9.8',
  activity:'30元店铺优惠券，满498元可用',
  count:'月销量38033',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/2705663075/TB20zlYbrBmpuFjSZFAXXaQ0pXa_!!2705663075.jpg',
      'https://gd1.alicdn.com/imgextra/i1/2705663075/TB2KtFVbrJmpuFjSZFBXXXaZXXa_!!2705663075.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'甜辣',
      brand:'微辣',
      city:'麻辣',
    },
    ARG:[
      {
        n:'商品名称',
        c:'君仔大刀肉',
      },
      {
        n:'商品产地',
        c:'中国大陆',
      },
      {
        n:'生产厂商',
        c:'君仔',
      },
      {
        n:'商品口味',
        c:'麻辣',
      }
    ]
  },
  comment:[
    {
      name:'哈哈啊哈哈',
      stars:4.5,
      date:'2017年3月24日',
      content:'宝贝特别好吃，吃多了有点微辣，跟图片上的一样，立体一包的也特干净，没有油腻腻的，送的炒米也特别好吃，以为会送小麻花的',
      picture:[
      ],
      browse:2041,
      praise:21,
    },
    {
      name:'我****子',
      stars:3,
      date:'2016年12月30日',
      content:'包装跟之前朋友买的和小时候那种不是一样的，9.8的辣条包邮还送了一个小东西，哈哈感觉占便宜了，快递也是很快就到了哦，只是我没有去拿总是忘记确认而已，信的字写的不错哈哈哈馋小乖有前途！?绝对好评的',
      picture:[],
      browse:113,
      praise:1,
    },
  ],
};

const cookie = {
  PROD_NO:8,
  SKU_NO:12,
  sel:1,
  image:'https://gd2.alicdn.com/imgextra/i3/555064954/TB21nGbbSKI.eBjy1zcXXXIOpXa_!!555064954.jpg',
  name:'御食园茯苓夹饼500g',
  price:'￥15.3',
  activity:'10元店铺优惠券，满198元可用',
  count:'月销量23456',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i2/555064954/TB2_7N9bSiJ.eBjSspfXXbBKFXa_!!555064954.jpg',
      'https://gd1.alicdn.com/imgextra/i1/555064954/TB2H3X7bNeI.eBjSsplXXX6GFXa_!!555064954.jpg',
      'https://gd2.alicdn.com/imgextra/i2/555064954/TB2TUVYbHaI.eBjy1XdXXcoqXXa_!!555064954.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'微甜',
      brand:'香甜',
      city:'无糖',
    },
    ARG:[
      {
        n:'商品名称',
        c:'茯苓夹饼',
      },
      {
        n:'商品产地',
        c:'中国大陆',
      },
      {
        n:'生产厂商',
        c:'御食园',
      },
      {
        n:'商品口味',
        c:'微甜',
      }
    ]
  },
  comment:[
    {
      name:'s***9',
      stars:5,
      date:'2017年3月24日',
      content:'·隔两天收到，物流走的比较快，收到箱子有点变形，好在没有破损。 ·茯苓夹饼整包拿在手里很有分量。打开是五种口味26小包。 ·尝了两个感觉味道差别没有很大，甜味儿明显。但馅儿的颜色是有区别的，以及馅儿是真的大~ ·总体上来说很不错，饼入口即化，馅儿比较爽口，价格也实惠，会考虑回购。',
      picture:[
      ],
      browse:32,
      praise:32,
    },
    {
      name:'w****k',
      stars:4,
      date:'2016年12月30日',
      content:'花生碎末或是其他好吃食品碎末等“内容”，而正是此“内容”方是北京特有特产茯苓夹饼的过人之处。昨天到货后，今天在分享到我团队成员们的礼袋中时，我才品尝了一枚，感觉到有些失望；又拿了一枚给曾经在北京工兵司令部住家生活了多年和在北京读书了多年的我母亲品尝了，母亲只是说此饼做得很精致',
      picture:[],
      browse:1113,
      praise:2,
    },
  ],
};

const cake = {
  PROD_NO:9,
  SKU_NO:13,
  sel:1,
  image:'https://gd4.alicdn.com/imgextra/i3/405732159/TB22exTdXXXXXXAXXXXXXXXXXXX_!!405732159.jpg',
  name:'祥禾枣泥卷酥',
  price:'￥24.9',
  activity:'单笔订单满66元免运费',
  count:'月销量4456',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/405732159/TB2krg3aXXXXXaCXpXXXXXXXXXX_!!405732159.jpg',
      'https://gd3.alicdn.com/imgextra/i3/405732159/TB2qLsRaai5V1BjSszbXXb0hVXa_!!405732159.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'微甜',
      brand:'香甜',
      city:'无糖',
    },
    ARG:[
      {
        n:'商品名称',
        c:'天津枣泥卷',
      },
      {
        n:'商品产地',
        c:'天津',
      },
      {
        n:'生产厂商',
        c:'什锦糕',
      },
      {
        n:'商品口味',
        c:'微甜',
      }
    ]
  },
  comment:[
    {
      name:'p***花',
      stars:5,
      date:'2017年4月02日',
      content:'外层的皮比想象中厚一点，这个外皮很酥，不是西式糕点那种细腻的口感，有点粗糙，但配上里面细腻绵柔的枣泥馅，简直完美。枣泥的馅比我想象中的要好很多，第一口下去是甜甜的，好比豆沙馅，再回味一下，竟觉得有些些苦。我在南方上学比较嗜甜，个人觉得甜度适中，饭后吃一块不用喝水也不觉得腻，妈妈就觉得有点点甜了，吃一块必须要喝水，我爸呢，只觉得外面的皮的太干，不过也表扬了內馅很棒，只能说口感因人而异。对了，每个都是密封包装，一共有12块',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'梦****k',
      stars:4,
      date:'2017年4月09日',
      content:'挺好吃的，做茶点不错，酥皮的一咬掉渣，单吃太干。枣泥馅的小时候经常吃到，好多糕点都爱放。当时不算太爱吃，只是觉得稀罕，因为只有家里来亲戚送的才有的吃，自己家都不怎么舍得买的，那时候家家生活不宽裕都穷嘛，现在惦记着这个味有很大的怀旧情感在里面。包装复古日期新鲜，应该是现做现卖的，我是拍了两三天才开始发货的。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const shupian = {
  PROD_NO:10,
  SKU_NO:14,
  sel:1,
  image:'https://gd2.alicdn.com/imgextra/i2/2768384747/TB2bb9_oFXXXXbEXXXXXXXXXXXX_!!2768384747.jpg',
  name:'KAKA咔咔龙虾饼',
  price:'￥15.80',
  activity:'单笔订单满66元免运费',
  count:'月销量4777',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i2/2768384747/TB2bb9_oFXXXXbEXXXXXXXXXXXX_!!2768384747.jpg',
      'https://gd4.alicdn.com/imgextra/i4/2768384747/TB2YZWQoFXXXXagXpXXXXXXXXXX_!!2768384747.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'甜辣',
      brand:'微辣',
      city:'麻辣',
    },
    ARG:[
      {
        n:'商品名称',
        c:'KAKA咔咔龙虾饼',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'KAKA食品厂',
      },
      {
        n:'商品口味',
        c:'甜辣',
      }
    ]
  },
  comment:[
    {
      name:'菱***爱（匿名）',
      stars:5,
      date:'2017年4月02日',
      content:'（?ò ? ó?）这个超好吃的，虽然物流有点慢，但是味道没让人失望。 (?°з°)-?服务超好的，给客服一个赞?。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'t***1（匿名）',
      stars:4,
      date:'2017年4月09日',
      content:'物流很快，但是买了之后店家说没有海苔味了，觉得退款麻烦，就换了芝士味，个人不喜欢',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const moyushuang = {
  PROD_NO:11,
  SKU_NO:15,
  sel:1,
  image:'https://gd4.alicdn.com/imgextra/i4/1991550352/TB2q76udMxlpuFjy0FoXXa.lXXa_!!1991550352.jpg',
  name:'卫龙馋魔芋爽',
  price:'￥22.30',
  activity:'单笔订单满66元免运费',
  count:'月销量1332',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/1991550352/TB2q76udMxlpuFjy0FoXXa.lXXa_!!1991550352.jpg',
      'https://gd4.alicdn.com/imgextra/i4/1991550352/TB2eHvTXF55V1Bjy0FoXXbVjFXa_!!1991550352.jpg',
      'https://gd3.alicdn.com/imgextra/i3/1991550352/TB2gAPMXGe5V1BjSspkXXcoqpXa_!!1991550352.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'甜辣',
      brand:'微辣',
      city:'麻辣',
    },
    ARG:[
      {
        n:'商品名称',
        c:'卫龙馋魔芋爽',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'卫龙辣条厂',
      },
      {
        n:'商品口味',
        c:'麻辣',
      }
    ]
  },
  comment:[
    {
      name:'hiu*****uu（匿名）',
      stars:5,
      date:'2017年4月02日',
      content:'咳咳咳......，味道一流挺好吃的。就是找不到小时辣的不要不要的感觉了，想想当初买一根辣条上课和同桌一块躲在桌子底下吃辣的满头大汗.....哎，我就想知道为啥不辣了，害的我把两袋一下全吃完了。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'w8***ii（匿名）',
      stars:4,
      date:'2017年4月09日',
      content:'东西很好 很喜欢 店家人好发货快 下次还来购买的哈',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const zuming = {
  PROD_NO:12,
  SKU_NO:16,
  sel:1,
  image:'https://gd1.alicdn.com/imgextra/i3/0/TB13a_6OFXXXXabXFXXXXXXXXXX_!!0-item_pic.jpg',
  name:'祖名香逗卷100g/袋',
  price:'￥4.90',
  activity:'单笔订单满66元免运费',
  count:'月销量2312',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i3/0/TB13a_6OFXXXXabXFXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd2.alicdn.com/imgextra/i2/456061218/TB240GnbVXXXXbmXXXXXXXXXXXX_!!456061218.png',
    ],
    option:{
      kouwei:'口味',
      name:'甜辣',
      brand:'微辣',
      city:'麻辣',
    },
    ARG:[
      {
        n:'商品名称',
        c:'祖名香逗卷',
      },
      {
        n:'商品产地',
        c:'浙江',
      },
      {
        n:'生产厂商',
        c:'祖名臭豆腐食品厂',
      },
      {
        n:'商品口味',
        c:'麻辣',
      }
    ]
  },
  comment:[
    {
      name:'wd**WGW',
      stars:5,
      date:'2017年4月02日',
      content:'有点厚 不入味',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'duudiid',
      stars:4,
      date:'2017年4月09日',
      content:'跟我想象的不太一样 不是很辣 挺好吃的但是',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const sumomo = {
  PROD_NO:13,
  SKU_NO:17,
  sel:1,
  image:'https://gd1.alicdn.com/imgextra/i3/264741757/TB2inLEabBmpuFjSZFAXXaQ0pXa_!!264741757.jpg',
  name:'酥嬷嬷蛋酥25g/包',
  price:'￥1.88',
  activity:'单笔订单满66元免运费',
  count:'月销量5990',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/264741757/TB2z.fGbVXXXXbjXpXXXXXXXXXX_!!264741757.png',
      'https://gd1.alicdn.com/imgextra/i3/264741757/TB2inLEabBmpuFjSZFAXXaQ0pXa_!!264741757.jpg',
      'https://gd1.alicdn.com/imgextra/i3/264741757/TB2inLEabBmpuFjSZFAXXaQ0pXa_!!264741757.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'微甜',
      brand:'香甜',
      city:'无糖',
    },
    ARG:[
      {
        n:'商品名称',
        c:'酥嬷嬷蛋酥',
      },
      {
        n:'商品产地',
        c:'天津',
      },
      {
        n:'生产厂商',
        c:'酥嬷嬷食品有限公司',
      },
      {
        n:'商品口味',
        c:'甜',
      }
    ]
  },
  comment:[
    {
      name:'232332990WSD',
      stars:5,
      date:'2017年4月01日',
      content:'买的太多了，整整两箱！就不一一评价了！我把每样都尝了一遍！感觉都吃着不错！额……也可能因为我是个吃货的原因！至于生产日期基本上都是今年二月跟三月份的，仅有一样是去年十二月份的，不过保质期是十二个月不影响什么！总之非常满意！祝老板生意兴隆！吃完再来买！',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'do8889OO0',
      stars:4,
      date:'2017年4月01日',
      content:'买了多次，这次50包本来原味和曼越味各25结果全寄了曼越味，家里人口味不一样的',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const badanmu = {
  PROD_NO:14,
  SKU_NO:18,
  sel:1,
  image:'https://gd3.alicdn.com/imgextra/i1/81331324/TB24AgWkHFkpuFjy1XcXXclapXa_!!81331324.jpg',
  name:'盐焗巴旦木仁500g',
  price:'￥36.9',
  activity:'单笔订单满66元免运费',
  count:'月销量1230',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i1/81331324/TB24AgWkHFkpuFjy1XcXXclapXa_!!81331324.jpg',
      'https://gd2.alicdn.com/imgextra/i2/81331324/TB2JsKcfFXXXXaJXXXXXXXXXXXX_!!81331324.jpg',
      'https://gd1.alicdn.com/imgextra/i1/81331324/TB26wadfFXXXXauXXXXXXXXXXXX_!!81331324.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'五香',
      brand:'奶油',
      city:'蒜味',
    },
    ARG:[
      {
        n:'商品名称',
        c:'盐焗巴旦木',
      },
      {
        n:'商品产地',
        c:'乌鲁木齐',
      },
      {
        n:'生产厂商',
        c:'八达食品有限公司',
      },
      {
        n:'商品口味',
        c:'咸香',
      }
    ]
  },
  comment:[
    {
      name:'w***Jkij',
      stars:5,
      date:'2017年4月03日',
      content:'刚寄来就打开尝了尝，味道可以，也没啥碎渣。挺满意……',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'io***oi',
      stars:4,
      date:'2017年4月01日',
      content:'评价方未及时做出评价,系统默认好评!',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

//母婴用品
const naiping = {
  PROD_NO:15,
  SKU_NO:19,
  sel:2,
  image:'https://gd3.alicdn.com/imgextra/i1/0/TB15RNEQpXXXXaUXVXXXXXXXXXX_!!0-item_pic.jpg',
  name:'玻璃奶瓶120ml-300ml',
  price:'￥22.4',
  activity:'10元店铺优惠券，满159元可用',
  count:'月销量231',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i1/0/TB15RNEQpXXXXaUXVXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd2.alicdn.com/imgextra/i2/418473073/TB2sJTzo5pnpuFjSZFkXXc4ZpXa_!!418473073.jpg',
      'https://gd2.alicdn.com/imgextra/i2/418473073/TB2kBkWmr8kpuFjy0FcXXaUhpXa_!!418473073.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'120ml',
      brand:'250ml',
      city:'300ml',
    },
    ARG:[
      {
        n:'商品名称',
        c:'玻璃奶瓶',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'福建贝贝孕婴用品有限公司',
      },
      {
        n:'商品规格',
        c:'300ml',
      }
    ]
  },
  comment:[
    {
      name:'OIInmnmm',
      stars:5,
      date:'2017年4月03日',
      content:'之前在这买的奶瓶被宝宝摔了，这次就买了两个奶瓶，我们家比较喜欢用标准口，之前买的没有吸管，这次买的有吸管宝宝还不习惯用，吸管过段时间再试试，奶瓶质量不错，刻度清晰，物廉价美，。客服很有耐心满足你的要求，照片跟实图一样就没拍了。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'23232222f',
      stars:4,
      date:'2017年4月01日',
      content:'第二次来了，质量很好，之前那个杯子也在他家买的，质量真的没话讲，被宝贝打破了又来买了，真的不错，价格也是实惠，值得推荐',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const zuobian = {
  PROD_NO:16,
  SKU_NO:20,
  sel:2,
  image:'https://gd1.alicdn.com/imgextra/i1/2946771980/TB2vrYvXai5V1BjSszcXXaDLXXa_!!2946771980.jpg',
  name:'儿童坐便器',
  price:'￥12.9',
  activity:'金币可抵0.25元',
  count:'月销量233',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i1/2946771980/TB2vrYvXai5V1BjSszcXXaDLXXa_!!2946771980.jpg',
      'https://gd1.alicdn.com/imgextra/i1/2946771980/TB2_CO0fNXlpuFjSsphXXbJOXXa_!!2946771980.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'儿童坐便器',
      },
      {
        n:'商品产地',
        c:'浙江',
      },
      {
        n:'生产厂商',
        c:'福建贝贝孕婴用品有限公司',
      },
      {
        n:'商品规格',
        c:'适合3岁以上儿童',
      }
    ]
  },
  comment:[
    {
      name:'w***j',
      stars:5,
      date:'2017年4月03日',
      content:'一体式比可拆洗的方便多了，质量好，料子结实，价格实惠，宝宝1岁5个月，23斤，坐着刚好。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'io*whit',
      stars:4,
      date:'2017年4月01日',
      content:'宝宝还没学会使用，都是用它当凳子用的。用料很厚实，我坐上去也没问题。还送了一个海洋球，很满意的一次网购。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const zhiniaoku = {
  PROD_NO:17,
  SKU_NO:21,
  sel:2,
  image:'https://gd4.alicdn.com/imgextra/i3/693174449/TB2lvhRXp15V1Bjy1XaXXaPqVXa_!!693174449.jpg',
  name:'妈咪宝贝婴儿纸尿裤',
  price:'￥35.5',
  activity:'单笔订单满66元免运费',
  count:'月销量432',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i3/693174449/TB2lvhRXp15V1Bjy1XaXXaPqVXa_!!693174449.jpg',
      'https://gd4.alicdn.com/imgextra/i3/693174449/TB2lvhRXp15V1Bjy1XaXXaPqVXa_!!693174449.jpg',
      'https://gd2.alicdn.com/imgextra/i2/693174449/TB2XbVwdFXXXXbsXpXXXXXXXXXX_!!693174449.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'日用',
      brand:'夜用',
      city:'全天',
    },
    ARG:[
      {
        n:'商品名称',
        c:'妈咪宝贝纸尿裤',
      },
      {
        n:'商品产地',
        c:'杭州',
      },
      {
        n:'生产厂商',
        c:'妈咪宝贝卫生用品',
      },
      {
        n:'商品规格',
        c:'夜用型加厚',
      }
    ]
  },
  comment:[
    {
      name:'ee***er',
      stars:5,
      date:'2017年4月03日',
      content:'妈咪宝贝既经济又实惠，一直用妈咪宝贝，下次还在叮小当买。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'23***0u878',
      stars:4,
      date:'2017年4月01日',
      content:'尿不湿还是不错的就是没有腰部弹力的很不好用，还想着薄还行再买的，好评后找客服要优惠券，可客服非要按照卡片的步骤来，',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const naifen = {
  PROD_NO:18,
  SKU_NO:22,
  sel:2,
  image:'https://gd4.alicdn.com/imgextra/i4/913961194/TB23iKMsVXXXXcHXXXXXXXXXXXX_!!913961194.jpg',
  name:'荷兰牛栏婴儿奶粉',
  price:'￥49.9',
  activity:'单笔订单满66元免运费',
  count:'月销量533',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/913961194/TB23iKMsVXXXXcHXXXXXXXXXXXX_!!913961194.jpg',
      'https://gd4.alicdn.com/imgextra/i4/913961194/TB2HP3SorJmpuFjSZFwXXaE4VXa_!!913961194.jpg',
      'https://gd2.alicdn.com/imgextra/i2/913961194/TB2A8zgjXXXXXbvXpXXXXXXXXXX_!!913961194.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'1-3岁',
      brand:'1-3月',
      city:'3-12月',
    },
    ARG:[
      {
        n:'商品名称',
        c:'荷兰牛栏婴儿奶粉',
      },
      {
        n:'商品产地',
        c:'荷兰',
      },
      {
        n:'生产厂商',
        c:'荷兰牛栏山奶粉厂',
      },
      {
        n:'商品规格',
        c:'1Kg',
      }
    ]
  },
  comment:[
    {
      name:'天***天',
      stars:5,
      date:'2017年4月02日',
      content:'没有，宝宝吃了没什么问题，宝宝很爱吃，已经快吃完了，马上就要再买了，第二灌也只有肿么一点了',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'今晚销魂',
      stars:4,
      date:'2017年4月03日',
      content:'连着买两次四罐，有效期还是五月份。日期再新鲜点就好',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const fennai = {
  PROD_NO:19,
  SKU_NO:23,
  sel:2,
  image:'https://gd2.alicdn.com/imgextra/i2/25983838/TB2OCtOcolnpuFjSZFjXXXTaVXa_!!25983838.jpg',
  name:'诺优能婴幼儿奶粉',
  price:'￥150.5',
  activity:'单笔订单满66元免运费',
  count:'月销量44',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i2/25983838/TB2OCtOcolnpuFjSZFjXXXTaVXa_!!25983838.jpg',
      'https://gd1.alicdn.com/imgextra/i1/25983838/TB2CAUHc9FjpuFjSszhXXaBuVXa_!!25983838.jpg',
      'https://gd4.alicdn.com/imgextra/i4/25983838/TB2iLb3XNfxQeBjSsppXXXeoFXa_!!25983838.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'1-3岁',
      brand:'1-3月',
      city:'3-12月',
    },
    ARG:[
      {
        n:'商品名称',
        c:'诺优能婴儿奶粉',
      },
      {
        n:'商品产地',
        c:'荷兰',
      },
      {
        n:'生产厂商',
        c:'荷兰牛栏山',
      },
      {
        n:'商品规格',
        c:'1Kg',
      }
    ]
  },
  comment:[
    {
      name:'buza**a',
      stars:5,
      date:'2017年4月03日',
      content:'第一次买诺诺家的奶粉和我之前直邮的，对比了外包装都是一样的，相信诺诺应该室正品，连现货都没有，都是直邮的。别看啦！诺诺来家里拍的视频都是在超市拍的，相信应该是正品，没有问题的，等喝过了再来追评。谢谢卖家赠品巧克力好吃',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'N***b',
      stars:4,
      date:'2017年4月04日',
      content:'10天到 给力 18年到期 送了巧克力 很好吃噢',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const yunqituo = {
  PROD_NO:20,
  SKU_NO:24,
  sel:2,
  image:'https://gd3.alicdn.com/imgextra/i3/110082491/TB2kM7pjNBmpuFjSZFsXXcXpFXa_!!110082491.jpg',
  name:'孕妇拖腹带',
  price:'￥49.00',
  activity:'单笔订单满66元免运费',
  count:'月销量43',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/110082491/TB2kM7pjNBmpuFjSZFsXXcXpFXa_!!110082491.jpg',
      'https://gd2.alicdn.com/imgextra/i2/110082491/TB291JOXnPC11Bjy1zcXXbTrVXa_!!110082491.jpg',
      'https://gd4.alicdn.com/imgextra/i3/110082491/TB2.ZfIil0kpuFjSsppXXcGTXXa_!!110082491.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'孕妇托腹带',
      },
      {
        n:'商品产地',
        c:'北京',
      },
      {
        n:'生产厂商',
        c:'北京孕婴有限公司',
      },
      {
        n:'商品规格',
        c:'xxl加大版',
      }
    ]
  },
  comment:[
    {
      name:'我是帅B',
      stars:5,
      date:'2017年4月03日',
      content:'怀孕8个月走路太累、腰酸的很！肚子坠坠的感觉明显！买了这个用起来！缓解腰痛！质量很好很棉质',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'我***B',
      stars:4,
      date:'2017年4月01日',
      content:'东西到了，质量和图一样，手感挺不错，昨天才用的，感觉效果挺好的，出去散步的时候带，感觉不到太坠',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const fuchanxie = {
  PROD_NO:21,
  SKU_NO:25,
  sel:2,
  image:'https://gd2.alicdn.com/imgextra/i4/13883804/TB2JrYTajzyQeBjy1zdXXaInpXa_!!13883804.jpg',
  name:'时尚产妇夏季月子鞋',
  price:'￥49.00',
  activity:'金币可抵0.98元',
  count:'月销量345',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i4/13883804/TB2JrYTajzyQeBjy1zdXXaInpXa_!!13883804.jpg',
      'https://gd2.alicdn.com/imgextra/i2/13883804/TB2ZZhCatfB11BjSspmXXctQVXa_!!13883804.jpg',
      'https://gd1.alicdn.com/imgextra/i1/13883804/TB2HESCcUWO.eBjSZPcXXbopVXa_!!13883804.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'月子鞋',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州皮鞋厂',
      },
      {
        n:'商品规格',
        c:'43号',
      }
    ]
  },
  comment:[
    {
      name:'落***漂',
      stars:5,
      date:'2017年4月03日',
      content:'很舒服。。平时穿三六码的鞋，，这次买的三六三七码的好好刚。。本人脚小肥。。很满意的一次网购……',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'小***家',
      stars:4,
      date:'2017年4月01日',
      content:'评价方未及时做出评价,系统默认好评!',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const yunfuzhuang = {
  PROD_NO:22,
  SKU_NO:26,
  sel:2,
  image:'https://gd3.alicdn.com/imgextra/i2/0/T1uXnCFjVdXXXXXXXX_!!0-item_pic.jpg',
  name:'婷美防辐射孕妇装',
  price:'￥259.00',
  activity:'免运费',
  count:'月销量5',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i2/0/T1uXnCFjVdXXXXXXXX_!!0-item_pic.jpg',
      'https://gd4.alicdn.com/imgextra/i4/733054173/T2Z24WX7hXXXXXXXXX_!!733054173.jpg',
      'https://gd3.alicdn.com/imgextra/i3/733054173/T2vQBWX5BXXXXXXXXX_!!733054173.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'防辐射孕妇装',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州制衣厂',
      },
      {
        n:'商品规格',
        c:'加肥加大',
      }
    ]
  },
  comment:[
    {
      name:'h***4',
      stars:5,
      date:'2017年4月03日',
      content:'不好穿',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'放***g',
      stars:4,
      date:'2017年4月01日',
      content:'评价方未及时做出评价,系统默认好评!',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const yunfumao = {
  PROD_NO:23,
  SKU_NO:27,
  sel:2,
  image:'https://gd4.alicdn.com/imgextra/i4/781073156/TB2pUQHatXnpuFjSZFoXXXLcpXa_!!781073156.jpg',
  name:'纯棉坐月子帽子',
  price:'￥15.8',
  activity:'单笔订单满66元免运费',
  count:'月销量1230',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/781073156/TB2pUQHatXnpuFjSZFoXXXLcpXa_!!781073156.jpg',
      'https://gd2.alicdn.com/imgextra/i2/781073156/TB2EsdCehxmpuFjSZFNXXXrRXXa_!!781073156.jpg',
      'https://gd3.alicdn.com/imgextra/i3/781073156/TB2LcH_bNXlpuFjSsphXXbJOXXa_!!781073156.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'孕妇帽',
      },
      {
        n:'商品产地',
        c:'台湾',
      },
      {
        n:'生产厂商',
        c:'台湾茵茵孕婴用品',
      },
      {
        n:'商品规格',
        c:'大头围',
      }
    ]
  },
  comment:[
    {
      name:'w***Jkij',
      stars:5,
      date:'2017年4月03日',
      content:'质量一般，刚开始有味道很刺鼻，现在洗了还好。不像是纯棉的。也不懂是什么料子，反正就是两层，这两个月用应该还可以。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'io***oi',
      stars:4,
      date:'2017年4月01日',
      content:'质量一般，刚开始有味道很刺鼻，现在洗了还好。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

//保健品
const danbaifen = {
  PROD_NO:24,
  SKU_NO:28,
  sel:3,
  image:'https://gd1.alicdn.com/imgextra/i4/1470033/TB2rJc7X1YC11Bjy1zkXXaZdXXa_!!1470033.jpg',
  name:'纽崔莱蛋白质粉',
  price:'￥255.0',
  activity:'10元店铺优惠券，满498元可用',
  count:'月销量524',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i4/1470033/TB2rJc7X1YC11Bjy1zkXXaZdXXa_!!1470033.jpg',
      'https://gd2.alicdn.com/imgextra/i2/1470033/TB2VGXXoXXXXXXCXFXXXXXXXXXX_!!1470033.jpg',
      'https://gd2.alicdn.com/imgextra/i2/1470033/TB2HLlMoXXXXXayXXXXXXXXXXXX_!!1470033.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'纽崔莱蛋白质粉',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'福建纽崔莱',
      },
      {
        n:'商品功用',
        c:'增加蛋白质',
      }
    ]
  },
  comment:[
    {
      name:'wdwddwd',
      stars:5,
      date:'2017年4月03日',
      content:'给爷爷买的，问了说不错应该是正品(原来买了好几年的一家不卖了，后来换了一家不过据爷爷奶奶说味道不对，又重新选了这家)',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'wd***djhdj',
      stars:4,
      date:'2017年4月01日',
      content:'十几年的老客户了，好商品',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const yingyangsu = {
  PROD_NO:25,
  SKU_NO:29,
  sel:3,
  image:'https://gd1.alicdn.com/imgextra/i1/88507047/TB2bKD3nHxmpuFjSZJiXXXauVXa_!!88507047.jpg',
  name:'澳佳宝黄金营养素',
  price:'￥178.0',
  activity:'单笔订单满66元免运费',
  count:'月销量234',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i1/88507047/TB2bKD3nHxmpuFjSZJiXXXauVXa_!!88507047.jpg',
      'https://gd3.alicdn.com/imgextra/i3/88507047/TB2lf5znFXXXXXwXpXXXXXXXXXX_!!88507047.jpg',
      'https://gd2.alicdn.com/imgextra/i2/88507047/TB2xEzicreI.eBjSspkXXaXqVXa_!!88507047.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'黄金营养素',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'澳佳宝营养集团',
      },
      {
        n:'商品功用',
        c:'提供复合营养',
      }
    ]
  },
  comment:[
    {
      name:'wodjjjjjj',
      stars:5,
      date:'2017年4月03日',
      content:'宝贝不错，同事让给买的，是正品。棒棒哒',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'niiuiudd',
      stars:4,
      date:'2017年4月01日',
      content:'特别棒～一直都是叮当家买～',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const weishengsu = {
  PROD_NO:26,
  SKU_NO:30,
  sel:3,
  image:'https://gd2.alicdn.com/imgextra/i1/88507047/TB2bq8pi4hmpuFjSZFyXXcLdFXa_!!88507047.jpg',
  name:'维生素咀嚼片',
  price:'￥80.00',
  activity:'单笔订单满66元免运费',
  count:'月销量1230',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i1/88507047/TB2bq8pi4hmpuFjSZFyXXcLdFXa_!!88507047.jpg',
      'https://gd2.alicdn.com/imgextra/i2/88507047/TB2AbBylXXXXXbQXXXXXXXXXXXX_!!88507047.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'含糖',
      brand:'无糖',
      city:'果味',
    },
    ARG:[
      {
        n:'商品名称',
        c:'维生素咀嚼片',
      },
      {
        n:'商品产地',
        c:'哈尔滨',
      },
      {
        n:'生产厂商',
        c:'哈尔滨制药六厂',
      },
      {
        n:'商品功用',
        c:'增加维生素',
      }
    ]
  },
  comment:[
    {
      name:'v88***jj',
      stars:5,
      date:'2017年4月03日',
      content:'为啥国外做的东西这么好看，包装好，口味也好，而且日期很新鲜，宝宝很喜欢，吃完还会再来回购的。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'mu***ooo',
      stars:5,
      date:'2017年4月01日',
      content:'评价方未及时做出评价,系统默认好评!',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const ribenwei = {
  PROD_NO:27,
  SKU_NO:31,
  sel:3,
  image:'https://gd1.alicdn.com/imgextra/i1/2048252919/TB2aLO_dB8lpuFjy0FnXXcZyXXa_!!2048252919.jpg',
  name:'日本DHC维生素',
  price:'￥38.00',
  activity:'单笔订单满66元免运费',
  count:'月销量12',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i1/2048252919/TB2aLO_dB8lpuFjy0FnXXcZyXXa_!!2048252919.jpg',
      'https://gd4.alicdn.com/imgextra/i4/2048252919/TB23PK.dB8kpuFjSspeXXc7IpXa_!!2048252919.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'DHC维生素',
      },
      {
        n:'商品产地',
        c:'日本',
      },
      {
        n:'生产厂商',
        c:'日本DHC集团',
      },
      {
        n:'商品功用',
        c:'增强体质',
      }
    ]
  },
  comment:[
    {
      name:'w***Jkij',
      stars:5,
      date:'2017年4月03日',
      content:'刚吃 这种只能补充维生素 美白是没什么效果的',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'io***oi',
      stars:4,
      date:'2017年4月01日',
      content:'不知道有没有效果，只求不中毒不伤身体就行',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const nvxingwei = {
  PROD_NO:28,
  SKU_NO:32,
  sel:3,
  image:'https://gd4.alicdn.com/imgextra/i2/55313688/TB26myMdSFmpuFjSZFrXXayOXXa_!!55313688.jpg',
  name:'女性复合维生素',
  price:'￥228.00',
  activity:'10元店铺优惠券，满1000元可用',
  count:'月销量134',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i2/55313688/TB26myMdSFmpuFjSZFrXXayOXXa_!!55313688.jpg',
      'https://gd2.alicdn.com/imgextra/i2/55313688/TB23lGwfctnpuFjSZFKXXalFFXa_!!55313688.jpg',
      'https://gd2.alicdn.com/imgextra/i2/55313688/TB2LxqFixBmpuFjSZFsXXcXpFXa_!!55313688.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'复合维生素',
      },
      {
        n:'商品产地',
        c:'唐山',
      },
      {
        n:'生产厂商',
        c:'唐山第二食品厂',
      },
      {
        n:'商品功用',
        c:'增加复合维生素',
      }
    ]
  },
  comment:[
    {
      name:'w***w9',
      stars:5,
      date:'2017年4月03日',
      content:'配合排油丸吃的，可以补充减肥期间必须的维生素，就是药味重了点，而且个头好大，对于我这种不喜欢吃药的人是种痛苦',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'o***ohhh',
      stars:4,
      date:'2017年4月06日',
      content:'这款产品，我是配合排油丸一起吃的。吃之前我也联系了客服该怎么吃，客服很耐心的回答了我。只不过太有一点味道，但是刚开始有点受不了，后来慢慢接受的。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const dasuansu = {
  PROD_NO:29,
  SKU_NO:33,
  sel:3,
  image:'https://gd3.alicdn.com/imgextra/i4/2330183943/TB24oDOavPB11BjSsppXXcjYVXa_!!2330183943.jpg',
  name:'大蒜油胶囊',
  price:'￥12.80',
  activity:'单笔订单满66元免运费',
  count:'月销量119000',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/2330183943/TB2CGaobVHzQeBjSZFuXXanUpXa_!!2330183943.jpg',
      'https://gd4.alicdn.com/imgextra/i4/2330183943/TB2W.TVaA6z11Bjy0FoXXbvkpXa_!!2330183943.jpg',
      'https://gd3.alicdn.com/imgextra/i4/2330183943/TB24oDOavPB11BjSsppXXcjYVXa_!!2330183943.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'大蒜油胶囊',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'福建宏源食品有限公司',
      },
      {
        n:'商品功用',
        c:'保持口气持久清新',
      }
    ]
  },
  comment:[
    {
      name:'tt****uk',
      stars:5,
      date:'2017年4月03日',
      content:'产品质量好，价格低。卖家服务态度好。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'UU8889oj',
      stars:4,
      date:'2017年4月01日',
      content:'给我妈买据说治疗糖尿病',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const luanhuangsu = {
  PROD_NO:30,
  SKU_NO:34,
  sel:3,
  image:'https://gd1.alicdn.com/imgextra/i3/0/TB1_nLgQpXXXXXmapXXXXXXXXXX_!!0-item_pic.jpg',
  name:'黑蒜卵黄营养素',
  price:'￥219.00',
  activity:'金币可抵4.38元',
  count:'月销量122',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i3/0/TB1_nLgQpXXXXXmapXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd1.alicdn.com/imgextra/i1/TB1N_KOPVXXXXbhXXXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd1.alicdn.com/imgextra/i1/2486360548/TB26tiAoXXXXXbbXXXXXXXXXXXX_!!2486360548.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'黑蒜卵黄营养素',
      },
      {
        n:'商品产地',
        c:'福建',
      },
      {
        n:'生产厂商',
        c:'福建宏源食品厂',
      },
      {
        n:'商品功用',
        c:'持续美白牙齿',
      }
    ]
  },
  comment:[
    {
      name:'w***Jkij',
      stars:5,
      date:'2017年4月03日',
      content:'目前为止，血糖很稳定，关键还是要一般吃这个一边控制饮食。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'io***oi',
      stars:4,
      date:'2017年4月01日',
      content:'老人才做了粘连手术，医生说要促进肠蠕动以免重新粘连，推荐了黑蒜，说黑蒜还可以增强免疫力和防三高。吃了些天了，润肠通气。肚子不像前几天老是胀胀 的。至于增强免疫力还没证明，吃段时间了来追加。老弟总是感冒，准备推荐给他试试',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const baobaolu = {
  PROD_NO:31,
  SKU_NO:35,
  sel:3,
  image:'https://gd1.alicdn.com/imgextra/i2/2961416058/TB2OKpkaPzyQeBjy0FeXXbwyFXa_!!2961416058.jpg',
  name:'宝露露维生素',
  price:'￥5.50',
  activity:'单笔订单满66元免运费',
  count:'月销量1110',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i2/2961416058/TB2OKpkaPzyQeBjy0FeXXbwyFXa_!!2961416058.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2961416058/TB2elxlaPzyQeBjy0FjXXc5CVXa_!!2961416058.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2961416058/TB2EoRraGbyQeBjy1XbXXa9yXXa_!!2961416058.jpg',
    ],
    option:{
      kouwei:'口味',
      name:'果味',
      brand:'奶味',
      city:'咸味',
    },
    ARG:[
      {
        n:'商品名称',
        c:'宝宝露维生素',
      },
      {
        n:'商品产地',
        c:'韩国',
      },
      {
        n:'生产厂商',
        c:'韩国现代有限公司',
      },
      {
        n:'商品功用',
        c:'增强体质',
      }
    ]
  },
  comment:[
    {
      name:'云云我',
      stars:5,
      date:'2017年4月03日',
      content:'产品质量好，价格低。卖家服务态度好。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'天哦哦哦',
      stars:4,
      date:'2017年4月01日',
      content:'产品质量好，价格低。卖家服务态度好。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const luoxuanzao = {
  PROD_NO:32,
  SKU_NO:36,
  sel:3,
  image:'https://gd2.alicdn.com/imgextra/i1/349759077/TB21BM4kipnpuFjSZFkXXc4ZpXa_!!349759077.jpg',
  name:'天然螺旋藻',
  price:'￥128.00',
  activity:'100元店铺优惠券，满4000元可用',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i1/349759077/TB21BM4kipnpuFjSZFkXXc4ZpXa_!!349759077.jpg',
      'https://gd1.alicdn.com/imgextra/i1/349759077/TB2xiiRe1tTMeFjSZFOXXaTiVXa_!!349759077.jpg',
      'https://gd1.alicdn.com/imgextra/i1/349759077/TB29p4fkr4npuFjSZFmXXXl4FXa_!!349759077.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中年',
      brand:'青年',
      city:'老年',
    },
    ARG:[
      {
        n:'商品名称',
        c:'天然螺旋藻',
      },
      {
        n:'商品产地',
        c:'新疆',
      },
      {
        n:'生产厂商',
        c:'新疆戈壁滩海洋生物有限公司',
      },
      {
        n:'商品功用',
        c:'无需调味炒着吃',
      }
    ]
  },
  comment:[
    {
      name:'八点半',
      stars:5,
      date:'2017年4月03日',
      content:'等吃过一段时间会追评的，既然是保健品，效果肯定不是立竿见影的，需要长时间服用，如果没有副作用会坚持服用的。图三图四图五是左旋右碱，我把胶囊打开了，因为个人喜欢拆开胶囊吃，是白色粉末，尝了一下白色粉末很酸，我很喜欢这个味道?',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'天涯明月',
      stars:4,
      date:'2017年4月01日',
      content:'程海湖螺旋藻片忘记吃，过期，都浪费掉了。试试德国的。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

//厨具
const guochantao = {
  PROD_NO:33,
  SKU_NO:37,
  sel:4,
  image:'https://gd4.alicdn.com/imgextra/i4/0/TB1GrD4IVXXXXbVXXXXXXXXXXXX_!!0-item_pic.jpg',
  name:'厨房锅铲套装',
  price:'￥38.9',
  activity:'单笔订单满80元免运费',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/0/TB1GrD4IVXXXXbVXXXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd3.alicdn.com/imgextra/i3/844068869/TB2SM7DbFXXXXXdXpXXXXXXXXXX_!!844068869.jpg',
      'https://gd2.alicdn.com/imgextra/i2/844068869/TB2fmMHbFXXXXbIXXXXXXXXXXXX_!!844068869.jpg',
    ],
    option:{
      kouwei:'材质',
      name:'金属',
      brand:'木质',
      city:'硅胶',
    },
    ARG:[
      {
        n:'商品名称',
        c:'厨房锅铲套装',
      },
      {
        n:'商品产地',
        c:'义务',
      },
      {
        n:'生产厂商',
        c:'义务小商品厂',
      },
      {
        n:'商品材质',
        c:'金属',
      }
    ]
  },
  comment:[
    {
      name:'耀武扬威',
      stars:5,
      date:'2017年4月03日',
      content:'宝贝是不锈钢的，很有质感，物美价廉，比超市的便宜多了。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'iiomccc',
      stars:4,
      date:'2017年4月01日',
      content:'宝贝很实用，它收纳了做饭的全部工具，起到了归类整理作用，用得很顺手，给好评',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const zhiwujia = {
  PROD_NO:34,
  SKU_NO:38,
  sel:4,
  image:'https://gd4.alicdn.com/imgextra/i1/1674818888/TB2tCPadl0kpuFjy1zdXXXuUVXa_!!1674818888.jpg',
  name:'厨房收纳置物架',
  price:'￥17.9',
  activity:'20元店铺优惠券，满238元可用',
  count:'月销量1876',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i1/1674818888/TB2tCPadl0kpuFjy1zdXXXuUVXa_!!1674818888.jpg',
      'https://gd3.alicdn.com/imgextra/i3/1674818888/TB2pJH2cthvOuFjSZFBXXcZgFXa_!!1674818888.jpg',
      'https://gd4.alicdn.com/imgextra/i4/1674818888/TB2L_ljiNBmpuFjSZFsXXcXpFXa_!!1674818888.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'厨房收纳置物架',
      },
      {
        n:'商品产地',
        c:'义务',
      },
      {
        n:'生产厂商',
        c:'义务小商品厂',
      },
      {
        n:'商品材质',
        c:'合成材质',
      }
    ]
  },
  comment:[
    {
      name:'哪那么多',
      stars:5,
      date:'2017年4月03日',
      content:'宝贝收到了，质量挺好的，本人很喜欢，唯一的缺点是筷子盒太短了，但不影响使用，放不了筷子可以拍大的，我准备再拍一单大号的',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'h***jj',
      stars:4,
      date:'2017年4月01日',
      content:'中号装28头餐盘够够的，很好。没什么味道，拿出来洗洗就用了。就是沥水篮拿着容易卡手指，放碗的一面很光滑，反面比较毛糙一点。还有卡扣的地方比较粗糙，有点小遗憾。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const guajia = {
  PROD_NO:35,
  SKU_NO:39,
  sel:4,
  image:'https://gd3.alicdn.com/imgextra/i3/59506532/TB2gRSwaxlmpuFjSZPfXXc9iXXa_!!59506532.png',
  name:'挂架置物架',
  price:'￥35.00',
  activity:'100元店铺优惠券，满4000元可用',
  count:'月销量11230',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/59506532/TB2gRSwaxlmpuFjSZPfXXc9iXXa_!!59506532.png',
      'https://gd1.alicdn.com/imgextra/i1/59506532/TB2LPKAemiK.eBjSZFyXXaS4pXa_!!59506532.jpg',
      'https://gd4.alicdn.com/imgextra/i4/59506532/TB2x62LhCBjpuFjy1XdXXaooVXa_!!59506532.png',
    ],
    option:{
      kouwei:'规格',
      name:'三角式',
      brand:'平面式',
      city:'粘贴式',
    },
    ARG:[
      {
        n:'商品名称',
        c:'挂架置物架',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州日化',
      },
      {
        n:'商品材质',
        c:'合成材质',
      }
    ]
  },
  comment:[
    {
      name:'mmuulo',
      stars:5,
      date:'2017年4月03日',
      content:'质量还是不错的，这个价格买到很划算，全5分',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'nnnuuuyttu',
      stars:4,
      date:'2017年4月01日',
      content:'东西不错。这个价格买到很是划算。值得表扬5分',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const caidao = {
  PROD_NO:36,
  SKU_NO:40,
  sel:4,
  image:'https://gd2.alicdn.com/imgextra/i3/0/TB16xZOKVXXXXcSXpXXXXXXXXXX_!!0-item_pic.jpg',
  name:'不锈钢刀具',
  price:'￥150.00',
  activity:'100元店铺优惠券，满4000元可用',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i3/0/TB16xZOKVXXXXcSXpXXXXXXXXXX_!!0-item_pic.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'无印花',
      brand:'青龙花',
      city:'白虎花',
    },
    ARG:[
      {
        n:'商品名称',
        c:'不锈钢刀',
      },
      {
        n:'商品产地',
        c:'浙江',
      },
      {
        n:'生产厂商',
        c:'浙江厨具厂',
      },
      {
        n:'商品材质',
        c:'铁',
      }
    ]
  },
  comment:[
    {
      name:'mm**mm',
      stars:5,
      date:'2017年4月03日',
      content:'之前专柜买的，阿姨说这个没有之前的锋利，不知磨磨会不会好点',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'huhuMei',
      stars:4,
      date:'2017年4月01日',
      content:'应该是正品，老婆用了说跟以前的一样好用，以前用的是20年前买的单立人刀',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const quwanjia = {
  PROD_NO:37,
  SKU_NO:41,
  sel:4,
  image:'https://gd1.alicdn.com/imgextra/i2/2432881360/TB2CEbmeYXlpuFjSszfXXcSGXXa_!!2432881360.jpg',
  name:'不锈钢取碗夹',
  price:'￥13.8',
  activity:'10元店铺优惠券，满169元可用',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i2/2432881360/TB2CEbmeYXlpuFjSszfXXcSGXXa_!!2432881360.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2432881360/TB20kMeqFXXXXcUXpXXXXXXXXXX_!!2432881360.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2432881360/TB2z7QfqFXXXXcKXpXXXXXXXXXX_!!2432881360.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'中号',
      brand:'大号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'不锈钢取碗夹',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州日化',
      },
      {
        n:'商品材质',
        c:'不锈铁',
      }
    ]
  },
  comment:[
    {
      name:'z***f',
      stars:5,
      date:'2017年4月03日',
      content:'给老妈买的！第二次买了！好用极了',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'唯***淘',
      stars:4,
      date:'2017年4月01日',
      content:'挺实用的，以后蒸菜取盘就容易多了！',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const guijiaochan = {
  PROD_NO:38,
  SKU_NO:42,
  sel:4,
  image:'https://gd1.alicdn.com/imgextra/i2/666189116/TB2.gSutVXXXXXXXpXXXXXXXXXX_!!666189116.jpg',
  name:'硅胶铲子不粘锅',
  price:'￥39.60',
  activity:'40元店铺优惠券，满568元可用',
  count:'月销量1800',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i2/666189116/TB2.gSutVXXXXXXXpXXXXXXXXXX_!!666189116.jpg',
      'https://gd3.alicdn.com/imgextra/i3/666189116/TB242WytVXXXXcdXXXXXXXXXXXX_!!666189116.jpg',
      'https://gd4.alicdn.com/imgextra/i4/666189116/TB2xs1HtVXXXXbjXXXXXXXXXXXX_!!666189116.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'黑底白花',
      brand:'白底黑花',
      city:'纯色',
    },
    ARG:[
      {
        n:'商品名称',
        c:'硅胶铲子',
      },
      {
        n:'商品产地',
        c:'天津',
      },
      {
        n:'生产厂商',
        c:'天津五金用品厂',
      },
      {
        n:'商品材质',
        c:'塑料',
      }
    ]
  },
  comment:[
    {
      name:'88777787@qq.com',
      stars:5,
      date:'2017年4月03日',
      content:'质量真的很棒，不锈钢和硅胶材质很上档次，一看就知道是好东西',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'jjunuuiii',
      stars:4,
      date:'2017年4月01日',
      content:'没拍照片，收到了感觉不错，赠品很多也很好',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const zhenglong = {
  PROD_NO:39,
  SKU_NO:43,
  sel:4,
  image:'https://gd1.alicdn.com/imgextra/i4/2889792903/TB2kfwqj3xlpuFjSszbXXcSVpXa_!!2889792903.jpg',
  name:'日韩式蒸笼',
  price:'￥23.00',
  activity:'50元店铺优惠券，满598元可用',
  count:'月销量2390',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i4/2889792903/TB2kfwqj3xlpuFjSszbXXcSVpXa_!!2889792903.jpg',
      'https://gd1.alicdn.com/imgextra/i1/2889792903/TB2F3AIcF5N.eBjSZFvXXbvMFXa_!!2889792903.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2889792903/TB2d8sbchuI.eBjy0FdXXXgbVXa_!!2889792903.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'蒸笼',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州厨具厂',
      },
      {
        n:'商品材质',
        c:'合成材质',
      }
    ]
  },
  comment:[
    {
      name:'kkiuiui',
      stars:5,
      date:'2017年4月03日',
      content:'发货很快，质量没问题，颜值确实高，大小正合适做茄子煲啊，豆腐锅一类的菜',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'cnuuuh为',
      stars:4,
      date:'2017年4月01日',
      content:'看了很久的锅，对比了几家才选的在这里买，发货非当快，包装的也超好。店家人很好，服务特别周到！用锅煮了粥，太完美了！还会再来的。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const modaoqi = {
  PROD_NO:40,
  SKU_NO:44,
  sel:4,
  image:'https://gd3.alicdn.com/imgextra/i4/2808586914/TB2uIWPdcCO.eBjSZFzXXaRiVXa_!!2808586914.jpg',
  name:'磨刀器',
  price:'￥9.90',
  activity:'全场包邮',
  count:'月销量18299',
  detail:{
    imageAndDes:[
      'https://gd4.alicdn.com/imgextra/i4/2808586914/TB2MnA3cC1I.eBjy0FjXXabfXXa_!!2808586914.jpg',
      'https://gd3.alicdn.com/imgextra/i4/2808586914/TB2uIWPdcCO.eBjSZFzXXaRiVXa_!!2808586914.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2808586914/TB2IhMWcw1J.eBjy0FaXXaXeVXa_!!2808586914.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'磨刀器',
      },
      {
        n:'商品产地',
        c:'义务',
      },
      {
        n:'生产厂商',
        c:'义务小商品厂',
      },
      {
        n:'商品材质',
        c:'铁',
      }
    ]
  },
  comment:[
    {
      name:'mmmjjj',
      stars:5,
      date:'2017年4月03日',
      content:'感收到货时，感觉包装有点破，里面的东西没有损坏，但是看起来做工不是很好。不过按照盒子上的说明磨了一下菜刀，还真是挺快，就是简单地拉了几次，刀子明显比以前快了很多，所以说人不可以貌相，性价比还是很好的',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'youyouqiu',
      stars:4,
      date:'2017年4月01日',
      content:'五星好评，价廉实用。磨出来的刀刃是大角度的，所以虽然锋利，但比如切冻肉不像手磨菜刀，用力的角度需有变化',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const shaoshuihu = {
  PROD_NO:41,
  SKU_NO:45,
  sel:4,
  image:'https://gd4.alicdn.com/imgextra/i4/879079357/TB2Vb1QbQ5M.eBjSZFrXXXPgVXa_!!879079357.jpg',
  name:'烧水壶',
  price:'￥40.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i1/879079357/TB22faNbOGO.eBjSZFjXXcU9FXa_!!879079357.jpg',
      'https://gd2.alicdn.com/imgextra/i2/879079357/TB2iWeWbF5N.eBjSZFvXXbvMFXa_!!879079357.jpg',
      'https://gd1.alicdn.com/imgextra/i1/879079357/TB2LrpTXr8kpuFjy0FcXXaUhpXa_!!879079357.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'1000W',
      brand:'1500W',
      city:'2000W',
    },
    ARG:[
      {
        n:'商品名称',
        c:'烧水壶',
      },
      {
        n:'商品产地',
        c:'广州',
      },
      {
        n:'生产厂商',
        c:'广州水壶厂',
      },
      {
        n:'商品材质',
        c:'合成材质',
      }
    ]
  },
  comment:[
    {
      name:'mmuy**gg',
      stars:5,
      date:'2017年4月03日',
      content:'快递速度快包装完整，水壶的质量杠杠滴，材质厚实居家实用，水烧开可自动报警提醒，不用专门守到那儿等水开，设计造型高大上不占地方，最终评价:满意喜欢',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'jjjiuyiiy8',
      stars:4,
      date:'2017年4月01日',
      content:'漂亮！性价比很高！又美观又实用！就是买个4L的就好了，5L有点大！看来还要多买个水瓶！',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

//洗护
const jiukou = {
  PROD_NO:42,
  SKU_NO:46,
  sel:5,
  image:'https://gd1.alicdn.com/imgextra/i2/1789677714/TB24Ma0tVXXXXciXpXXXXXXXXXX_!!1789677714.jpg',
  name:'玖蔻精油套装',
  price:'￥148.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量1290',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i2/1789677714/TB24Ma0tVXXXXciXpXXXXXXXXXX_!!1789677714.jpg',
      'https://gd1.alicdn.com/imgextra/i1/1789677714/TB2M3mLithvOuFjSZFBXXcZgFXa_!!1789677714.jpg',
      'https://gd1.alicdn.com/imgextra/i1/1789677714/TB2OnhNppXXXXXWXpXXXXXXXXXX_!!1789677714.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'玫瑰',
      brand:'茉莉',
      city:'薰衣草',
    },
    ARG:[
      {
        n:'商品名称',
        c:'玖蔻精油套装',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州宝洁有限公司',
      },
      {
        n:'商品功用',
        c:'保湿除皱',
      }
    ]
  },
  comment:[
    {
      name:'nnu**yui',
      stars:5,
      date:'2017年4月03日',
      content:'洗后掉发严重，头发枯燥，毫无生气，看了下成份，里面含月桂醇，月桂醇是一种廉价的化学合成表面活性剂，刺激性很强，清洁力也很强，而且致癌，理发店洗头工的手部粗糙、蜕皮就是长期使用这类劣质洗发水照成的。垃圾货。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'W***w',
      stars:4,
      date:'2017年4月01日',
      content:'一直都买微商的！第一次在淘宝买！今天刚收到货！挤出一点闻了闻味道！跟微商的一模一样！应该是正品！主要比微商便宜多了！还会接着光顾得',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const taomishui = {
  PROD_NO:43,
  SKU_NO:47,
  sel:5,
  image:'https://gd2.alicdn.com/imgextra/i4/1017506346/TB2CVJTaORnpuFjSZFCXXX2DXXa_!!1017506346.jpg',
  name:'淘米水洗发水',
  price:'￥35.00',
  activity:'5元店铺优惠券，满99元可用',
  count:'月销量1070',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i4/1017506346/TB2CVJTaORnpuFjSZFCXXX2DXXa_!!1017506346.jpg',
      'https://gd4.alicdn.com/imgextra/i4/1017506346/TB2IzHodNuI.eBjy0FdXXXgbVXa_!!1017506346.jpg',
      'https://gd3.alicdn.com/imgextra/i3/1017506346/TB2GNl2fVXXXXaNXpXXXXXXXXXX_!!1017506346.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'淘米水洗发水',
      },
      {
        n:'商品产地',
        c:'唐山',
      },
      {
        n:'生产厂商',
        c:'唐山日化厂',
      },
      {
        n:'商品功用',
        c:'去屑无残留',
      }
    ]
  },
  comment:[
    {
      name:'mmuy**gg',
      stars:5,
      date:'2017年4月03日',
      content:'这款淘米洗发水很不错哦，想购买的朋友放心吧确实去头皮屑效果很不错，我非常满意。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'jjjiuyiiy8',
      stars:4,
      date:'2017年4月01日',
      content:'已经用过才来评价的 真的非常不错 还送精油 是我非常喜欢的味道 洗发水味道也很好 值得购买',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const xishutao = {
  PROD_NO:44,
  SKU_NO:48,
  sel:5,
  image:'https://gd1.alicdn.com/imgextra/i2/452645519/TB2knxEsXXXXXXFXpXXXXXXXXXX_!!452645519.jpg',
  name:'旅行洗漱套装',
  price:'￥40.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量1890',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i2/452645519/TB2knxEsXXXXXXFXpXXXXXXXXXX_!!452645519.jpg',
      'https://gd1.alicdn.com/imgextra/i1/452645519/TB2STkWnVXXXXarXXXXXXXXXXXX_!!452645519.png',
      'https://gd4.alicdn.com/imgextra/i4/452645519/TB2yfaViFXXXXXyXXXXXXXXXXXX_!!452645519.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'洗漱套装',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州宝洁有限公司',
      },
      {
        n:'商品功用',
        c:'便携旅行洗漱用品',
      }
    ]
  },
  comment:[
    {
      name:'晕**gg',
      stars:5,
      date:'2017年4月03日',
      content:'宝贝收到了 包装完整无破损 快递物流也很快 收到了是自己想要的 蓝色包包是自己的真爱 米色毛巾也超级棒 特别柔软 不掉毛 其实自己最喜欢里面的伸缩刷牙杯 感觉发明这个东西的人真是天才',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'莫iiiu',
      stars:4,
      date:'2017年4月01日',
      content:'东西超棒棒棒棒！开箱就是好香好香的味道～小熊维尼的漱口杯好可爱～没有洒的～',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const jiangli = {
  PROD_NO:45,
  SKU_NO:49,
  sel:5,
  image:'https://gd2.alicdn.com/imgextra/i2/2734034195/TB2UrhocSOI.eBjSspmXXatOVXa_!!2734034195.jpg',
  name:'姜力洗发水',
  price:'￥248.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量2301',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i2/2734034195/TB2UrhocSOI.eBjSspmXXatOVXa_!!2734034195.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2734034195/TB2_xVhcHmI.eBjy1zjXXaq5VXa_!!2734034195.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2734034195/TB2CYH7XBTxQeBjSspoXXcP7XXa_!!2734034195.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'姜力洗发水',
      },
      {
        n:'商品产地',
        c:'浙江',
      },
      {
        n:'生产厂商',
        c:'浙江姜力有限公司',
      },
      {
        n:'商品功用',
        c:'去腥不油腻',
      }
    ]
  },
  comment:[
    {
      name:'mmuy**g233',
      stars:5,
      date:'2017年4月03日',
      content:'去年11月买的，一套基本快用完了，说实话，真心是福利，以前头发大把大把的掉，现在洗一次头一共就掉10根，哈哈哈，真数过的，前面的小头发也长出来了不少，说实话以前真心不信这些东西，姜力真是改变了我的世界观呀哈哈哈，支持',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'jjj23344g',
      stars:4,
      date:'2017年4月01日',
      content:'宝贝收到，完好无损，很好的卖家还送了好多的小样，服务相当好，谢谢！待用着好的话会继续光顾，好卖家！',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const baima = {
  PROD_NO:46,
  SKU_NO:50,
  sel:5,
  image:'https://gd1.alicdn.com/imgextra/i3/2352285632/TB2HJwrl4BmpuFjSZFDXXXD8pXa_!!2352285632.jpg',
  name:'白妈无硅油',
  price:'￥98.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量3978',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i3/2352285632/TB2HJwrl4BmpuFjSZFDXXXD8pXa_!!2352285632.jpg',
      'https://gd1.alicdn.com/imgextra/i1/2352285632/TB2kKdkjVXXXXbLXXXXXXXXXXXX_!!2352285632.jpg',
      'https://gd4.alicdn.com/imgextra/i4/2352285632/TB2mi5Uf0hvOuFjSZFBXXcZgFXa_!!2352285632.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'白妈无硅油洗发水',
      },
      {
        n:'商品产地',
        c:'温州',
      },
      {
        n:'生产厂商',
        c:'温州白妈食品厂',
      },
      {
        n:'商品功用',
        c:'去屑不伤发',
      }
    ]
  },
  comment:[
    {
      name:'鱼鱼gg',
      stars:5,
      date:'2017年4月03日',
      content:'一直在这家购买，前几天又买了一套送老妈的，店家送了小裤裤，昨晚拆了一片，真的是用过最舒服的内裤式卫生巾非常赞，特意来写个评价',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'天天喝大力',
      stars:4,
      date:'2017年4月01日',
      content:'说实话买了这么长时间了 没感觉去头屑多好 和别的洗头的一样 还是有头屑 还 这么贵 差点忘了评论 今天看淘宝一下子想起来了 说的是真的 头上还有很多头屑 根本没有用',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const songbenrun = {
  PROD_NO:47,
  SKU_NO:51,
  sel:5,
  image:'https://gd2.alicdn.com/imgextra/i1/23763273/TB2vd82d1tTMeFjSZFOXXaTiVXa_!!23763273.jpg',
  name:'日本松本润',
  price:'￥56.00',
  activity:'5元店铺红包，满5.01元可用',
  count:'月销量2930',
  detail:{
    imageAndDes:[
      'https://gd3.alicdn.com/imgextra/i3/23763273/TB24qfUhNdkpuFjy0FbXXaNnpXa_!!23763273.jpg',
      'https://gd1.alicdn.com/imgextra/i1/23763273/TB2p8aGdhRDOuFjSZFzXXcIipXa_!!23763273.jpg',
      'https://gd4.alicdn.com/imgextra/i4/23763273/TB2vRmGdhRDOuFjSZFzXXcIipXa_!!23763273.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'松本润',
      },
      {
        n:'商品产地',
        c:'日本',
      },
      {
        n:'生产厂商',
        c:'日本松本株式会社',
      },
      {
        n:'商品功用',
        c:'润养去屑',
      }
    ]
  },
  comment:[
    {
      name:'艾妮马',
      stars:5,
      date:'2017年4月03日',
      content:'看了成分表，有一种氨基酸，这个在氨基酸洗发水中算平价。洗发水是透明液体，用过后头皮清爽，很舒服，头发蓬松，我属于油性头皮，头发干。',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'风风润润',
      stars:4,
      date:'2017年4月01日',
      content:'宝贝收到，感觉应该是正品，还没有用，所以不知道效果，等使用之后再评价',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const oba = {
  PROD_NO:48,
  SKU_NO:52,
  sel:5,
  image:'https://gd2.alicdn.com/imgextra/i3/68130803/TB2srnBemBjpuFjy1XdXXaooVXa_!!68130803.jpg',
  name:'欧芭洗护套装',
  price:'￥216.00',
  activity:'50元店铺优惠券，满499元可用',
  count:'月销量568',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i3/68130803/TB2srnBemBjpuFjy1XdXXaooVXa_!!68130803.jpg',
      'https://gd1.alicdn.com/imgextra/i1/68130803/TB2TZ2_k9xjpuFjSszeXXaeMVXa_!!68130803.jpg',
      'https://gd1.alicdn.com/imgextra/i1/68130803/TB2knBjaKrAQeBjSZFrXXbSvFXa_!!68130803.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'欧芭洗护套装',
      },
      {
        n:'商品产地',
        c:'韩国',
      },
      {
        n:'生产厂商',
        c:'韩国oba有限公司',
      },
      {
        n:'商品功用',
        c:'全套洗护',
      }
    ]
  },
  comment:[
    {
      name:'呜呜**我也',
      stars:5,
      date:'2017年4月03日',
      content:'同事介绍的这家店，刚收到货包装很细心，拆了膜香味扑鼻而来，很喜欢.赠品不错，还有包发膜。谢谢啦',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'急急急急',
      stars:4,
      date:'2017年4月01日',
      content:'还好咨询了下客服选了适合自己的型号，洗发乳质地挺稠，洗的时候头发冲湿透了，能揉搓很多细腻泡泡，很好洗。洗两遍后用点护发素在发尾，吹干头发好顺。。妈妈也说好用，很难得母亲大人夸一下。用完继续。',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const wowo = {
  PROD_NO:49,
  SKU_NO:53,
  sel:5,
  image:'https://gd2.alicdn.com/imgextra/i3/2964957688/TB2UPo4cItnpuFjSZFKXXalFFXa_!!2964957688.jpg',
  name:'蜗蜗洗发水',
  price:'￥108.00',
  activity:'20元店铺红包，满20.01元可用',
  count:'月销量1803',
  detail:{
    imageAndDes:[
      'https://gd2.alicdn.com/imgextra/i3/2964957688/TB2UPo4cItnpuFjSZFKXXalFFXa_!!2964957688.jpg',
      'https://gd3.alicdn.com/imgextra/i3/2964957688/TB2D9VjdtAvbeFjSspbXXbcOFXa_!!2964957688.jpg',
      'https://gd2.alicdn.com/imgextra/i2/2964957688/TB2DTUdfX5N.eBjSZFmXXboSXXa_!!2964957688.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'茉莉香',
      brand:'玫瑰香',
      city:'兰花香',
    },
    ARG:[
      {
        n:'商品名称',
        c:'蜗蜗洗发水',
      },
      {
        n:'商品产地',
        c:'韩国',
      },
      {
        n:'生产厂商',
        c:'韩国wowo有限公司',
      },
      {
        n:'商品功用',
        c:'洗发不伤发',
      }
    ]
  },
  comment:[
    {
      name:'mmuy**gg',
      stars:5,
      date:'2017年4月03日',
      content:'和之前在微商买的一样，正品很划算，还送了一面镜子，超喜欢，之前洗什么发水都不行，后来一直用蜗蜗，蜗止痒去屑，防掉发，么么哒',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'jjjiuyiiy8',
      stars:4,
      date:'2017年4月01日',
      content:'蜗蜗洗发水效果确实很好，对于头皮痒等问题得到了有效的缓解',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const xihudai = {
  PROD_NO:50,
  SKU_NO:54,
  sel:5,
  image:'https://gd1.alicdn.com/imgextra/i3/0/TB1gDWdNFXXXXaFXFXXXXXXXXXX_!!0-item_pic.jpg',
  name:'文胸洗护袋',
  price:'￥9.80',
  activity:'10元店铺优惠券，满168元可用',
  count:'月销量58990',
  detail:{
    imageAndDes:[
      'https://gd1.alicdn.com/imgextra/i3/0/TB1gDWdNFXXXXaFXFXXXXXXXXXX_!!0-item_pic.jpg',
      'https://gd4.alicdn.com/imgextra/i4/612316204/TB2Su9Wfd4opuFjSZFLXXX8mXXa_!!612316204.jpg',
    ],
    option:{
      kouwei:'规格',
      name:'大号',
      brand:'中号',
      city:'小号',
    },
    ARG:[
      {
        n:'商品名称',
        c:'文胸洗护袋',
      },
      {
        n:'商品产地',
        c:'浙江',
      },
      {
        n:'生产厂商',
        c:'浙江日百有限公司',
      },
      {
        n:'商品功用',
        c:'保护内衣不变形',
      }
    ]
  },
  comment:[
    {
      name:'天津小马哥',
      stars:5,
      date:'2017年4月03日',
      content:'物美价廉！很喜欢，感觉质量不错！有需要会再来的~总体很满意，网很细',
      picture:[
      ],
      browse:3232,
      praise:32,
    },
    {
      name:'poipoi*',
      stars:4,
      date:'2017年4月01日',
      content:'搭配着卖 关键是洗文胸的有用 另外一个尺寸太小 基本是鸡肋',
      picture:[],
      browse:1173,
      praise:102,
    },
  ],
};

const suoyou = {
  all:[jiangli,baima,songbenrun,oba,wowo,xihudai,jiukou,taomishui,xishutao,
  caidao,quwanjia,guijiaochan,zhenglong,modaoqi,guochantao,shaoshuihu,zhiwujia,guajia,
ribenwei,nvxingwei,luanhuangsu,baobaolu,luoxuanzao,dasuansu,danbaifen,yingyangsu,weishengsu,
fuchanxie,yunqituo,naiping,zuobian,zhiniaoku,fennai,naifen,yunfumao,yunfuzhuang,
moyushuang,zuming,sumomo,badanmu,cake,shupian,beef,hot,cookie]
}

const shouye = {
    choice:'热门推荐',
    choiceDetail:[badanmu,zuobian,luanhuangsu,zhenglong],
    like:'精品推荐',
    likeDetail:[jiangli,caidao,ribenwei,fuchanxie,moyushuang,baima,quwanjia,nvxingwei,yunqituo,zuming],
  };

const xihu = {
    choice:'洗护精选',
    choiceDetail:[jiukou,taomishui,xishutao],
    like:'精品洗护',
    likeDetail:[jiangli,baima,songbenrun,oba,wowo,xihudai,jiukou,taomishui,xishutao],
    mallDetail:[jiangli,baima,songbenrun,oba,wowo,xihudai]
  };

const chuju = {
    choice:'厨具精选',
    choiceDetail:[shaoshuihu,zhiwujia,guajia],
    like:'精品厨具',
    likeDetail:[caidao,quwanjia,guijiaochan,zhenglong,modaoqi,guochantao,shaoshuihu,zhiwujia,guajia],
    mallDetail:[caidao,quwanjia,guijiaochan,zhenglong,modaoqi,guochantao]
  };

const baojian = {
    choice:'保健精选',
    choiceDetail:[danbaifen,yingyangsu,weishengsu],
    like:'精品保健',
    likeDetail:[ribenwei,nvxingwei,luanhuangsu,baobaolu,luoxuanzao,dasuansu,danbaifen,yingyangsu,weishengsu],
    mallDetail:[ribenwei,nvxingwei,luanhuangsu,baobaolu,luoxuanzao,dasuansu]
  };

const muying = {
    choice:'母婴精选',
    choiceDetail:[naifen,yunfumao,yunfuzhuang],
    like:'精品母婴',
    likeDetail:[fuchanxie,yunqituo,naiping,zuobian,zhiniaoku,fennai,naifen,yunfumao,yunfuzhuang],
    mallDetail:[fuchanxie,yunqituo,naiping,zuobian,zhiniaoku,fennai]
  };

const foods = {
    choice:'零食精选',
    choiceDetail:[beef,hot,cookie],
    like:'精品零食',
    likeDetail:[moyushuang,zuming,sumomo,badanmu,cake,shupian,beef,hot,cookie],
    mallDetail:[moyushuang,zuming,sumomo,badanmu,cake,shupian]
  };


export default {
  foods,
  muying,
  baojian,
  chuju,
  xihu,
  shouye,
  suoyou,
}
